# config/packages/services.api.yaml
services:
  App\Service\SessionSigner:
    arguments:
      $secret: '%env(APP_SESSION_SECRET)%'

  App\Service\GameSessionService: ~
  App\Service\PuzzleValidationService: ~
  App\Service\HintService: ~
  App\Service\LeaderboardService: ~

  App\Controller\Api\SessionController: ~
  App\Controller\Api\AttemptController: ~
  App\Controller\Api\HintController: ~
  App\Controller\Api\LeaderboardController: ~
