name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Docker Compose
        run: |
          if command -v docker >/dev/null 2>&1; then
            docker compose config
          else
            echo "Docker not available on runner; skipping compose validation."
          fi
