name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: Shellcheck (si scripts sh)
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning

      - name: PHP lint (si PHP présent)
        run: |
          if command -v php >/dev/null 2>&1; then
            find . -type f -name "*.php" -print0 | xargs -0 -n1 -I{} php -l "{}"
          else
            echo "PHP non disponible dans l'environnement runner"
          fi
